### ISSUE TITLE
ROS 2 hl_rviz_marker

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/humanoid_league_visualization#31]

**Comment by SammyRamone** [comment]
I think we do not need to continue to use this package as the ros-sports messages already provide rviz markers. right? @Flova @jaagut

**Comment by Flova** [comment]
Correct they will be soon released for rolling

**Comment by jaagut** [comment]
This is it: https://github.com/ros-sports/soccer_vision_3d_rviz_markers
